### ISSUE TITLE
Not scrapping all photos.

### ISSUE THREAD

**Issue by biogk** [froulet/instagram-spider#1]
When there are multiple photos in one post, the spider is only scraping the first one.

**Comment by froulet** [comment]
Thanks for the feedback  @biogk !
I fixed it in the last commit.
https://github.com/froulet/instagram-spider/commit/677a0f764dda710c3b206bf30a9eb99024b87ef8

Don't hesitate to tell me if it's not working for you.

**Comment by biogk** [comment]
Thank you!
